#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; IMAGE="dokku/$APP"
echo "-----> Installing weasyprint ..."
COMMAND=$(cat <<EOF

export DEBIAN_FRONTEND=noninteractive
apt-get -y update
apt-get install -y build-essential python3-dev python3-pip python3-setuptools python3-wheel python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
echo "-----> install python3.6"

wget https://www.python.org/ftp/python/3.6.3/Python-3.6.3.tgz
tar -xvf Python-3.6.3.tgz
cd Python-3.6.3
./configure --enable-optimizations
make -j8
make install
python3.6 -V
python3.6 -m pip install requests
pip3 -V
echo "-----> pip3 install weasyprint"
pip3 install weasyprint
echo "-----> pip3 install cairocffi"
pip3 install cairocffi
echo "-----> weasyprint installed!"
sleep 1 # wait so that docker run has not exited before docker attach
EOF
)
id=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
#enable logs
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
